sudo: false

language: php, node_js

cache:
  directories:
    - $HOME/php/.composer/cache

node_js:
  - stable

branches:
  only:
  - master

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

before_script:
  - composer install --prefer-source

script:
  - composer test